spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hcymall?serverTimezone=GMT%2B8&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hcy1805110063
    type: com.alibaba.druid.pool.DruidDataSource
    # 如果没有 druid依赖，则不写下面 druid 的配置
    druid:
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 5000
mybatis-plus:
  type-aliases-package: com.hcy.entity
  mapper-locations: classpath:mapper/**.xml
server:
  port: 8079