---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hcy.
--- DateTime: 2022/3/5 2:40
--- 判断 该用户是否已经抢了优惠券，抢了 则返回 -1；购物券不够，返回 0；抢券成功，返回 1
local x = redis.call('get',KEYS[2]);
if x  then
    return "c"
end
--
local num = redis.call('get',KEYS[1])
if tonumber(num ) < 1 then
    -- 如果返回数字，java 必须用 Long 接收
    return "b"
end
redis.call('set',KEYS[1],(num-1))
redis.call('set',KEYS[2],1)
return "a"
